import { useEffect, useState } from "react";
import { ArrowUpRight, Sparkles } from "lucide-react";
import { Link } from "wouter";
import ProductCard from "@/components/ProductCard";
import { getCollections, getProducts, shopifyConfigured, type Collection, type Product } from "@/lib/store";

export default function Home() {
  const [products, setProducts] = useState<Product[]>([]); const [collections, setCollections] = useState<Collection[]>([]); const [error, setError] = useState("");
  useEffect(() => { if (!shopifyConfigured) return; Promise.all([getProducts({ first: 8, sortKey: "BEST_SELLING" }), getCollections(8)]).then(([items, groups]) => { setProducts(items); setCollections(groups); }).catch((cause) => setError(cause instanceof Error ? cause.message : "Unable to load the Liverton catalogue.")); }, []);
  return <>
    <section className="hero-section"><div className="hero-copy"><span className="eyebrow"><Sparkles size={13} /> Liverton Store</span><h1>Smart finds for <em>everyday living.</em></h1><p>Useful beauty essentials, kitchen upgrades, and thoughtful gadgets selected for life in motion.</p><div className="hero-actions"><Link href="/products" className="button button-brass">Shop the edit <ArrowUpRight size={16} /></Link><Link href="/products?collection=beauty" className="button button-quiet">Shop Beauty</Link></div></div><div className="hero-art"><div className="hero-art-shape shape-one" /><div className="hero-art-shape shape-two" /><div className="hero-art-card"><span>01</span><strong>Useful<br /><em>by design.</em></strong><small>Beauty · Kitchen · Gadgets</small></div></div></section>
    <section className="value-strip"><div><strong>Curated for everyday</strong><span>Products chosen for usefulness</span></div><div><strong>Shopify checkout</strong><span>Secure, familiar checkout</span></div><div><strong>Made for Uganda</strong><span>Clear local support information</span></div></section>
    <section className="section-pad"><div className="section-heading"><div><span className="eyebrow">Explore the edit</span><h2>Find your <em>new useful.</em></h2></div><Link href="/products" className="text-link">View all products <ArrowUpRight size={15} /></Link></div><div className="category-grid">{collections.slice(0, 4).map((collection) => <Link key={collection.id} href={`/products?collection=${collection.handle}`} className="category-card">{collection.image && <img src={collection.image.url} alt={collection.image.altText ?? collection.title} loading="lazy" />}<span>{collection.title}</span><ArrowUpRight size={17} /></Link>)}{!shopifyConfigured && <div className="empty-state"><h3>Connect Shopify to load your collections</h3><p>The storefront is ready for live products once the Storefront API variables are added.</p></div>}</div></section>
    <section className="section-pad product-section"><div className="section-heading"><div><span className="eyebrow">Shopify-powered</span><h2>Liverton <em>picks.</em></h2></div><Link href="/products" className="text-link">Shop everything <ArrowUpRight size={15} /></Link></div>{error ? <div className="empty-state"><h3>Catalogue unavailable</h3><p>{error}</p></div> : products.length ? <div className="product-grid home-product-grid">{products.slice(0, 4).map((product) => <ProductCard key={product.id} product={product} />)}</div> : <div className="empty-state"><h3>{shopifyConfigured ? "Your products will appear here" : "Shopify connection required"}</h3><p>{shopifyConfigured ? "Add products in Shopify and they will appear here automatically." : "Add the Shopify Storefront API variables in Vercel to activate the live catalogue."}</p></div>}</section>
    <section className="split-callout"><div><span className="eyebrow">Beauty & personal care</span><h2>Small rituals.<br /><em>Better days.</em></h2><Link href="/products?collection=beauty" className="button button-dark">Shop Beauty <ArrowUpRight size={15} /></Link></div><div className="callout-panel"><span>Liverton note</span><p>We look for the tools and essentials that make a daily routine feel simpler, calmer, and more considered.</p></div></section>
    <section className="faq-section section-pad"><div><span className="eyebrow">Good to know</span><h2>Shop with <em>confidence.</em></h2></div><div className="faq-list"><details open><summary>How does checkout work?</summary><p>Your bag is handled by Shopify and checkout opens on Shopify’s secure hosted checkout.</p></details><details><summary>Where can I find delivery information?</summary><p>Delivery, payment, and returns information should reflect the active policies configured for your Liverton Store.</p></details><details><summary>Can I get help choosing a product?</summary><p>Use the customer-support contact in the footer for current assistance options.</p></details></div></section>
  </>;
}
